#!/bin/sh
TARGET_DIR=../../../doxygen/qcsapi/latex
targetfile=${TARGET_DIR}/refman.tex
tmpfile=${TARGET_DIR}/refman.tex.tmp

if [ -f $targetfile ] ; then
	echo "refman.tex exists....."
	# change latex type from "book" to "report" , Change the default title generated by doxygen, remove chapters that we don't need
	sed -e 's/book/report/' -e 's/Module Documentation/QCSAPI detailed documentation/' \
		-e '/Module Index/',+1d \
		-e '/Data Structure Index/',+1d \
		$targetfile > $tmpfile

	cp -f $tmpfile $targetfile
fi
