/****************************************************************************
*
* Copyright (c) 2015  Quantenna Communications, Inc.
*
* Permission to use, copy, modify, and/or distribute this software for any
* purpose with or without fee is hereby granted, provided that the above
* copyright notice and this permission notice appear in all copies.
*
* THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
* WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
* MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
* SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
* RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
* NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE
* USE OR PERFORMANCE OF THIS SOFTWARE.
*
*****************************************************************************/

#ifndef QSIGMA_TAGS_H
#define QSIGMA_TAGS_H

enum qsigma_cmd_tags {
	QSIGMA_TAG_BASE = 0x1000,
	QSIGMA_AP_GET_INFO_TAG = QSIGMA_TAG_BASE,
	QSIGMA_AP_SET_RADIUS_TAG,
	QSIGMA_AP_SET_WIRELESS_TAG,
	QSIGMA_AP_RESET_DEFAULT_TAG,
	QSIGMA_AP_SET_11N_WIRELESS_TAG,
	QSIGMA_AP_SET_SECURITY_TAG,
	QSIGMA_AP_CA_VERSION_TAG,
	QSIGMA_AP_SET_PMF_TAG,
	QSIGMA_AP_SET_APQOS_TAG,
	QSIGMA_AP_SET_STAQOS_TAG,
	QSIGMA_AP_REBOOT_TAG,
	QSIGMA_AP_CONFIG_COMMIT_TAG,
	QSIGMA_AP_DEAUTH_STA_TAG,
	QSIGMA_AP_GET_MAC_ADDRESS_TAG,
	QSIGMA_AP_SET_11D_TAG,
	QSIGMA_AP_SET_11H_TAG,
	QSIGMA_AP_SET_RFEATURE_TAG,
	QSIGMA_AP_SET_HS2_TAG,

	/* STA */
	QSIGMA_STA_CA_GET_VERSION_TAG,
	QSIGMA_STA_RESET_DEFAULT_TAG,
	QSIGMA_STA_DEVICE_LIST_INTERFACES_TAG,
	QSIGMA_STA_PRESET_TESTPARAMETERS_TAG,
	QSIGMA_STA_DISCONNECT_TAG,
	QSIGMA_STA_SEND_ADDBA_TAG,
	QSIGMA_STA_GET_MAC_ADDRESS_TAG,
	QSIGMA_STA_GET_INFO_TAG,
	QSIGMA_STA_SET_WIRELESS_TAG,
	QSIGMA_STA_SET_RFEATURE_TAG,
	QSIGMA_STA_SET_IP_CONFIG_TAG,
	QSIGMA_STA_SET_PSK_TAG,
	QSIGMA_STA_ASSOCIATE_TAG,
	QSIGMA_STA_SET_ENCRYPTION_TAG,
	QSIGMA_DEV_SEND_FRAME_TAG,
	QSIGMA_STA_REASSOC_TAG,
	QSIGMA_STA_SET_SYSTIME_TAG,
	QSIGMA_STA_SET_RADIO_TAG,
	QSIGMA_STA_SET_MACADDR_TAG,
	QSIGMA_STA_SET_UAPSD_TAG,
	QSIGMA_STA_RESET_PARM_TAG,
	QSIGMA_STA_SET_11N_TAG,
	QSIGMA_STA_SET_POWER_SAVE_TAG,
	QSIGMA_STA_SET_SLEEP_TAG,
	QSIGMA_DEVICE_GET_INFO_TAG,
};

#endif				/* QSIGMA_TAGS_H */
