#
# Copyright (C) 2004, 2007-2010, 2011-2012 Synopsys, Inc. (www.synopsys.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

USE_STANDARD_AS_RULE := true

obj-y		+= extable.o iomap.o ioremap.o fault.o paging.o tlb.o tlbex.o

obj-y		+= init.o cache_arc700.o dma.o mmap.o

